### ISSUE TITLE
Issue in setting GSI/JEDI experiment using JEDI-T2O feature/gdas-vaidation branch

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/JEDI-T2O#105]
@CoryMartin-NOAA @RussTreadon-NOAA 
The `setup_workflow -c` and `setup_workflow -b` steps completed successfully.  
However, the `setup_workflow -s` step failed at sourcing config.verfozn step with the following error message:

```
+ ./setup_expt.py gfs cycled --idate 2021080100 --edate 2021080200 --app ATM --start warm --gfs_cyc 0 --resdet 768 --nens 0 --cdump gdas --pslot gdas_eval_atms_GSI --configdir /work2/noaa/da/eliu/gdas-validation/gdas_config --comrot /work2/noaa/da/eliu/gdas-validation/comrot --expdir /work2/noaa/da/eliu/gdas-validation/expdir --yaml /work2/noaa/da/eliu/gdas-validation/gdas_config/config_gsi.yaml --icsdir /work2/noaa/da/cmartin/UFO_eval/data/para/output_ufo_eval_aug2021/2021080100
EDITED:  /work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_GSI/config.base as per user input.
+ ./setup_expt.py gfs cycled --idate 2021080100 --edate 2021080200 --app ATM --start warm --gfs_cyc 0 --resdet 768 --nens 0 --cdump gdas --pslot gdas_eval_atms_JEDI --configdir /work2/noaa/da/eliu/gdas-validation/gdas_config --comrot /work2/noaa/da/eliu/gdas-validation/comrot --expdir /work2/noaa/da/eliu/gdas-validation/expdir --yaml /work2/noaa/da/eliu/gdas-validation/gdas_config/config_jedi.yaml --icsdir /work2/noaa/da/cmartin/UFO_eval/data/para/output_ufo_eval_aug2021/2021080100
EDITED:  /work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_JEDI/config.base as per user input.
EDITED:  /work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_JEDI/config.atmanl as per user input.
+ set +x
Finalizing initialize
sourcing config.prep
sourcing config.anal
sourcing config.analdiag
sourcing config.sfcanl
sourcing config.analcalc
sourcing config.fcst
sourcing config.upp
sourcing config.atmos_products
sourcing config.arch
sourcing config.cleanup
sourcing config.fit2obs
sourcing config.verfozn
/work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_GSI/config.verfozn: line 16: /work2/noaa/da/eliu/gdas-validation/global-workflow/parm/monitor/gdas_oznmon.parm: No such file or directory
Traceback (most recent call last):
  File "./setup_xml.py", line 79, in <module>
    main()
  File "./setup_xml.py", line 70, in main
    app_config = app_config_factory.create(f'{net}_{mode}', cfg)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/factory.py", line 71, in create
    return self._builders[key](*args, **kwargs)
  File "/work2/noaa/da/eliu/gdas-validation/global-workflow/workflow/applications/applications.py", line 22, in __call__
    obj._init_finalize(*args, **kwargs)
  File "/work2/noaa/da/eliu/gdas-validation/global-workflow/workflow/applications/applications.py", line 86, in _init_finalize
    self.configs = self._source_configs(conf)
  File "/work2/noaa/da/eliu/gdas-validation/global-workflow/workflow/applications/applications.py", line 153, in _source_configs
    configs[config] = conf.parse_config(files)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/configuration.py", line 82, in parse_config
    return cast_strdict_as_dtypedict(self._get_script_env(files))
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/configuration.py", line 98, in _get_script_env
    and_script_env = cls._get_shell_env(scripts)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/configuration.py", line 118, in _get_shell_env
    'at least one script failed: ' + repr(out))
wxflow.configuration.ShellScriptException: Cannot find magic string; at least one script failed: 'BEGIN: config.base\nBEGIN: config.com\nEND: config.base\nBEGIN: config.verfozn\nBEGIN: config.resources\nEND: config.resources\n': error processing/work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_GSI/config.base /work2/noaa/da/eliu/gdas-validation/expdir/gdas_eval_atms_GSI/config.verfozn
```

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , this is a known issue.   A fix has been develop and is undergoing testing on Orion and Hera.

**Comment by RussTreadon-NOAA** [comment]
The inability of `fv3jedi_var.x` to read C768 backgrounds and run the solver at C768 has been reported via fv3-jedi issue [#1108](https://github.com/JCSDA-internal/fv3-jedi/issues/1108).
